latent_motion_tokenizer_config_path: "/group/40101/milkcychen/Moto/latent_motion_tokenizer/configs/models/vq_size128_dim32_num8_legacyTrue-vision_MaeLarge-decoder_queryFusionModeAdd_Patch196_useMaskFalse-mformer_legacyTrue.yaml"
dataset_config_path: "/group/40101/milkcychen/Moto/latent_motion_tokenizer/configs/data/rtx.yaml"
dataloader_config:
  bs_per_gpu: 32
  workers_per_gpu: 7
  prefetch_factor: 2
rgb_preprocessor_config: 
  model_vision_type: "mae"
  vision_aug_config: 
    do_random_resized_crop: false
    do_random_shift: true
training_config:
  num_epochs: 20
  num_warmup_epochs: 1
  print_steps: 100
  lr_max: 0.0001
  weight_decay: 0.0001
  gradient_accumulation_steps: 2
  save_epochs: 1
  save_steps: 1000
  save_path: "/group/40101/milkcychen/Moto/latent_motion_tokenizer/outputs/latent_motion_tokenizer_trained_on_oxe/"
  resume_ckpt_path: null